spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    batch:
        job:
            enabled: true
        jdbc:
            initialize-schema: never
server:
    servlet:
        context-path: /fleamarketbatchprocessing
logging:
    level:
        '[com.example]': INFO
        '[com.zaxxer.hikari]': INFO
        '[org.springframework.boot.devtools.autoconfigure.OptionalLiveReloadServer]': INFO
        '[org.springframework.batch]': INFO
        '[org.springframework.jdbc.core]': INFO
        '[org.springframework.jdbc]': INFO
        '[org.springframework.batch.item.database]': INFO
        '[org.springframework.transaction]': INFO
        '[org.springframework.jdbc.datasource]': INFO
        '[org.springframework.batch.item.support]': INFO
        '[org.springframework.batch.core.configuration.annotation.BatchRegistrar]': INFO