spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/fleamarketbatchprocessing
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    batch:
        job:
            enabled: true
        jdbc:
            initialize-schema: never
server:
    servlet:
        context-path: /fleamarketbatchprocessing
logging:
    level:
        '[org.springframework.batch.item.database]': DEBUG
        '[org.springframework.batch]': DEBUG
        '[org.springframework.jdbc.core.JdbcTemplate]': DEBUG
        '[org.springframework.transaction]': DEBUG
        '[org.springframework.jdbc]': DEBUG
        '[org.springframework.jdbc.datasource]': DEBUG
        '[org.springframework.batch.item.support]': DEBUG