spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    batch:
        job:
            enabled: true
        jdbc:
            initialize-schema: never
server:
    servlet:
        context-path: /fleamarketbatchprocessing
    
