spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    batch:
        job:
            enabled: true
        jdbc:
            initialize-schema: never
server:
    servlet:
        context-path: /fleamarketbatchprocessing
logging:
    level:
        '[com.example]': WARN
        '[com.zaxxer.hikari]': ERROR
        '[org.springframework.boot.devtools.autoconfigure.OptionalLiveReloadServer]': ERROR
        '[org.springframework.batch]': ERROR
        '[org.springframework.jdbc.core]': ERROR
        '[org.springframework.jdbc]': ERROR
        # '[org.springframework.batch.item.database]': INFO
        # '[org.springframework.transaction]': INFO
        # '[org.springframework.jdbc.datasource]': INFO
        # '[org.springframework.batch.item.support]': INFO