spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/gs-batch-processing
        username: postgres
        driver-class-name: org.postgresql.Driver
    batch:
        job:
            enabled: true
        jdbc:
            initialize-schema: never
server:
    servlet:
        context-path: /gs-batch-processing
logging:
    level:
        '[org.springframework.batch.item.database]': DEBUG
        '[org.springframework.batch]': DEBUG
        '[org.springframework.jdbc.core.JdbcTemplate]': DEBUG
        '[org.springframework.transaction]': DEBUG
        '[org.springframework.jdbc]': DEBUG
        '[org.springframework.jdbc.datasource]': DEBUG
        '[org.springframework.batch.item.support]': DEBUG